### ISSUE TITLE
Minibatch code?

### ISSUE THREAD

**Issue by Gdls** [uyaseen/theano-recurrence#2]
Hi, uyaseen ! Thanks for your codes. I want to know will you update a copy with minibatch?

**Comment by uyaseen** [comment]
Hi, actually mini-batch version should not be very difficult to implement, you just have to use dimshuffle(..), currently, I am very busy with my Master Thesis, I can only provide a mini-batch version after I am done with that but it can take a while.

**Comment by Gdls** [comment]
OK，thank you! I will finish it!
